USE MASTER
GO
USE CSe21A_FSIII_Simulator
GO

CREATE TABLE [Class]
(
    [ID] INT IDENTITY,
    [Name] NVARCHAR(200) NULL,

    CONSTRAINT Class_ID PRIMARY KEY (ID)
)

CREATE TABLE[Person]
(
    [ID] INT IDENTITY,
    [FirstName] NVARCHAR(80) NULL,
    [LastName] NVARCHAR(80) NULL,
    [Role] NVARCHAR(20) NOT NULL,

    CONSTRAINT P_ID PRIMARY KEY (ID)
)

CREATE TABLE [Teacher]
(
    [ID] INT,
    CONSTRAINT Teacher_ID PRIMARY KEY (ID),
    CONSTRAINT P_ID FOREIGN KEY (ID) REFERENCES Person(ID)
)

CREATE TABLE [Classteachers]
(
    [Teacher_ID] INT,
    [Class_ID] INT,

    CONSTRAINT Class_Teacher_ID PRIMARY KEY (Teacher_ID, Class_ID),
    CONSTRAINT Teacher_ID FOREIGN KEY (Teacher_ID) REFERENCES Teacher(ID),
    CONSTRAINT Class_ID FOREIGN KEY (Class_ID) REFERENCES Class(ID)
)


CREATE TABLE [Student](
    [ID] INT,
    [Class_ID] int,

    CONSTRAINT Student_ID PRIMARY KEY (ID),
    CONSTRAINT P_ID FOREIGN KEY (ID) REFERENCES Person(ID),
    CONSTRAINT FK_Class_ID FOREIGN KEY (Class_ID) REFERENCES Class(ID)

)

CREATE TABLE [Credentials]
(
    [ID] INT,
    [Password] NVARCHAR(100) NOT NULL,

    CONSTRAINT ID PRIMARY KEY (ID, Password),
    CONSTRAINT P_ID FOREIGN KEY (ID) REFERENCES Person(ID)
)